name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 4. Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5. Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 6. Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 7. Build Release APK (unsigned)
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      # 8. Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartWebView-Debug
          path: app/build/outputs/apk/debug/*.apk

      # 9. Upload Release AP
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartWebView-Release
          path: app/build/outputs/apk/release/*.apk
