name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # ✅ Decode google-services.json kalau ada secret
      - name: Decode google-services.json
        if: ${{ secrets.GOOGLE_SERVICES_JSON != '' }}
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      # ✅ Kalau secret kosong → disable plugin google-services
      - name: Disable Google Services if no secret
        if: ${{ secrets.GOOGLE_SERVICES_JSON == '' }}
        run: |
          echo "⚠️ No google-services.json provided. Disabling Firebase plugin..."
          sed -i '/com.google.gms.google-services/s/^/\/\/ /' app/build.gradle

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartWebView-Debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartWebView-Release
          path: app/build/outputs/apk/release/*.apk
